export const intents = [
  {
    name: "greeting",
    patterns: [
      "hi",
      "hello",
      "hey",
      "howdy",
      "hola",
      "bonjour",
      "oi",
      "ola",
      "aloha",
      "ciao",
      "namaste",
    ],
    responses: ["Hello!", "Hi!", "Hey there!"],
  },
  {
    name: "goodbye",
    patterns: ["bye", "goodbye", "see you later", "take care"],
    responses: ["Goodbye!", "See you later!", "Take care!"],
  },
  {
    name: "thanks",
    patterns: ["thanks", "thank you", "appreciate it"],
    responses: ["You're welcome!", "No problem!", "Anytime!"],
  },
  {
    name: "laughter",
    patterns: [
      "haha!",
      "lol!",
      "hehe!",
      "lmao",
      "😂",
      "😆",
      "🤣",
      "lol",
      "😂😂😂",
      "haha",
      "😆😆😆",
      "🤣🤣🤣",
    ],
    responses: [
      "😂",
      "😆",
      "🤣",
      "LOL",
      "😂😂😂",
      "Haha",
      "😆😆😆",
      "🤣🤣🤣",
      "LMAO",
    ],
  },
  {
    name: "starter",
    patterns: ["start", "begin", "let's go", "let's start"],
    responses: [
      "Where are you travelling from",
      "What is your current location",
      "Where are you now",
    ],
  },
  {
    name: "unknown",
    responses: [
      "I'm sorry, I don't understand.",
      "Can you please try again?",
      "I didn't catch that.",
    ],
  },
];
